### PR TITLE
Made IBAnimatable a shared scheme

### PR DESCRIPTION
**Pull request by delannoyk**
That makes the framework Carthage compatible (#6).

Also, if you merge this, you'll probably want to tag the commit to a version number.

### CODE REVIEW

**Comment by JakeLin** [comment]
Thank you very much.

**Comment by JakeLin** [comment]
Thanks again, I have tagged it as [V1.0.1](https://github.com/JakeLin/IBAnimatable/releases/tag/V1.0.1) and will update readme to support Carthage.

**Comment by JakeLin** [comment]
@delannoyk Sorry to bother you, I am having some issues with Carthage support. I created an example project and added a Cartfile at https://github.com/JakeLin/IBAnimatable-PackageManagementExamples/blob/master/IBAnimatable-Carthage/Cartfile

When I ran `carthage update`, then I got some errors like

```
*** Fetching IBAnimatable
*** Checking out IBAnimatable at "V1.0.1"
*** xcodebuild output can be found in /var/folders/r9/2nsd0w6d2mn87jkg75njd3md14_q5m/T/carthage-xcodebuild.lQfGCo.log
*** Building scheme "IBAnimatable" in IBAnimatableApp.xcodeproj
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator9.2.sdk/usr/include/sys/cdefs.h:707:2: error: Unsupported architecture
...
...
...

The following build commands failed:
    CompileSwift normal arm64 /Users/jake.lin/dev/Jake/IBAnimatable-PackageManagementExamples/IBAnimatable-Carthage/Carthage/Checkouts/IBAnimatable/IBAnimatable/AnimatableButton.swift
    CompileSwift normal arm64 /Users/jake.lin/dev/Jake/IBAnimatable-PackageManagementExamples/IBAnimatable-Carthage/Carthage/Checkouts/IBAnimatable/IBAnimatable/RotationDesignable.swift
    CompileSwift normal arm64 /Users/jake.lin/dev/Jake/IBAnimatable-PackageManagementExamples/IBAnimatable-Carthage/Carthage/Checkouts/IBAnimatable/IBAnimatable/AnimatableLabel.swift
    CompileSwift normal arm64 /Users/jake.lin/dev/Jake/IBAnimatable-PackageManagementExamples/IBAnimatable-Carthage/Carthage/Checkouts/IBAnimatable/IBAnimatable/AnimatableStackView.swift
    CompileSwift normal arm64 /Users/jake.lin/dev/Jake/IBAnimatable-PackageManagementExamples/IBAnimatable-Carthage/Carthage/Checkouts/IBAnimatable/IBAnimatable/MaskType.swift
    CompileSwift normal arm64 /Users/jake.lin/dev/Jake/IBAnimatable-PackageManagementExamples/IBAnimatable-Carthage/Carthage/Checkouts/IBAnimatable/IBAnimatable/AnimatableTableView.swift
    CompileSwift normal arm64 /Users/jake.lin/dev/Jake/IBAnimatable-PackageManagementExamples/IBAnimatable-Carthage/Carthage/Checkouts/IBAnimatable/IBAnimatable/Animatable.swift
    CompileSwift normal arm64 /Users/jake.lin/dev/Jake/IBAnimatable-PackageManagementExamples/IBAnimatable-Carthage/Carthage/Checkouts/IBAnimatable/IBAnimatable/AnimatableTextField.swift
    CompileSwiftSources normal arm64 com.apple.xcode.tools.swift.compiler
(9 failures)
```

I followed the doc from https://github.com/Carthage/Carthage#resolve-build-failures 

I `cd` to `/Users/jake.lin/dev/jake/IBAnimatable-PackageManagementExamples/IBAnimatable-Carthage/Carthage/Checkouts/IBAnimatable` and executed `xcodebuild -scheme IBAnimatable -project IBAnimatableApp.xcodeproj -configuration release build` and succeeded to build the the framework target like below:

```
=== BUILD TARGET IBAnimatable OF PROJECT IBAnimatableApp WITH THE DEFAULT CONFIGURATION (Release) ===

Check dependencies

** BUILD SUCCEEDED **
```

That's my first time to support Carthage, can you give me some hint when you have time?

Thanks
Jake

**Comment by JakeLin** [comment]
I find something interesting. Once I added `-sdk iphonesimulator` to `xcodebuild` like 

`xcodebuild -scheme IBAnimatable -project IBAnimatableApp.xcodeproj -sdk iphonesimulator -configuration release build`

Then I got this: 
`/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator9.2.sdk/usr/include/sys/cdefs.h:707:2: error: Unsupported architecture
#error Unsupported architecture`

Something wrong with `-sdk iphonesimulator`

**Comment by delannoyk** [comment]
This is interesting, that's a problem I didn't have using my fork.

Anyway, I tried with a Cartfile containing: 
`github "JakeLin/IBAnimatable"`

And I don't have the same error you have:

```
*** Building scheme "IBAnimatable" in IBAnimatableApp.xcodeproj
xcodebuild: error: Unable to find a destination matching the provided destination specifier:
        { platform:iOS Simulator, id:A13AE2E7-4EB7-4165-9DFC-332BB80C8E24 }
A shell task failed with exit code 70:
xcodebuild: error: Unable to find a destination matching the provided destination specifier:
        { platform:iOS Simulator, id:A13AE2E7-4EB7-4165-9DFC-332BB80C8E24 }
```

I'm at work right now but I'll definitely take a deeper look at it when I'll come home later today!

**Comment by delannoyk** [comment]
I'm not having any issues on my personal laptop. Weird.

```
~/D/t ❯❯❯ carthage update                                                     ⏎
*** Fetching IBAnimatable
*** Checking out IBAnimatable at "V1.0.1"
*** xcodebuild output can be found in /var/folders/ws/xc68hw2j7kb5l6hqtmz0kh7m0000gn/T/carthage-xcodebuild.BDvtiE.log
*** Building scheme "IBAnimatable" in IBAnimatableApp.xcodeproj
~/D/t ❯❯❯
```

And the framework is built successfully.

**Comment by lastMove** [comment]
@JakeLin  Which version of carthage do you have ? you should have the 0.11.
I just tried to built your framework from carthage and it works.
Be sure to have the latest version.

**Comment by JakeLin** [comment]
@delannoyk  @lastMove Thanks guys, I installed Carthage using `Carthage.pkg` long time ago, and used `brew install carthage` to install again. But didn't notice I had old version of Carthage. I have fixed this issue by uninstalling the older version.

**Pull request merged**
