### PR TITLE
Embedded xcodeprojs in workspace #no-public-changes

### PR DESCRIPTION
**Pull request by tbaranes**
First step for #479 

- No code updates
- Adding `IBAnimatable.xcworkspace`
- Adding two new xcodeproj:
    - `IBAnimatable.xcodeproj` (framework)
    - `IBAnimatableApp.xcodeproj` (demo / playground). In a long term process, I'm even wondering if we shouldn't make two demos: one for the _full_ demo, and a second one for playgrounds 
- Reorganising sources: map Xcode groups with finder (I may have broken a few groups orders in Xcode, I will reorganise them if the PR is approved)
- Updating paths for: travis, danger, cocoapods
- Move all the framework sources in a directory `Sources`

One question: I know that, from the beginning, we separate storyboards and codes in the demo app. I'm personally a huge fan of this pattern because I find it hard to navigate, and find back the related files. What do you guys prefers about this? If you are ok to group them, I can update the PR.

I'm targeting master because it doesn't introduce any breaking changes, only internal restructuration, but it will be very hard to rebase any PRs due to these changes 😬

### CODE REVIEW

**Comment by SD10** [comment]
@tbaranes you mean group each storyboard file with its respective view controller?

I do it both ways depending on the project. I agree that grouping them together would significantly help when working with the demo app. I would vote yes for this change 👍

**Comment by tbaranes** [comment]
That what I mean!

**Comment by tbaranes** [comment]
I just reordered xcodeproj groups (same as master), I think it's ready to go. My question about the storyboards organisation still here, but we can do it in a second a PR. If travis passes, and everything is ok with it, it's ok to go 💥

**Review by JakeLin — APPROVED** [review]
👍 I think we need to update the README.md as well. `open IBAnimatable.xcworkspace`

**Comment by JakeLin** [comment]
>One question: I know that, from the beginning, we separate storyboards and codes in the demo app. I'm personally a huge fan of this pattern because I find it hard to navigate, and find back the related files. What do you guys prefers about this? If you are ok to group them, I can update the PR.

I prefer to group them by features. I don't know why I did it that way (separating storyboards and codes)

**Pull request merged**
