### PR TITLE
Add ellipse mask type

### PR DESCRIPTION
**Pull request by phimage**
Add missing `triangle` in demo

First attempt on `MaskType`
I have others mask to propose, I will make an issue 
#482

### CODE REVIEW

**Review by JakeLin — APPROVED** [review]
Nice one, and with UI tests in the demo app 👍

**Comment by JakeLin** [comment]
@phimage nice one, looking forward to seeing the sharps in #482 too. Can you please update the CHANGLOG.md or you want to treat it as one item for all masks in #482? Please merge it when you free ready, thanks 👍

**Review by tbaranes — APPROVED** [review]

**Comment by tbaranes** [comment]
Travis is failing because Danger has reported "CHANGELOG missing", once the entry added, travis should be green!

**Comment by phimage** [comment]
I know, no PR could be done in one commit, even the little one 😭 

And when I will merge this one with CHANGELOG update, I have some probability of having conflict with #478 💀 
So I will wait for 478 merge

**Comment by tbaranes** [comment]
If you really want only one commit, you can amend the changelog update in your branch, then force push. It will make this PR ready to go with one commit only!

**Comment by JakeLin** [comment]
@phimage well done 🎉🎉🎉

**Pull request merged**
