### PR TITLE
Danger support

### LINKED ISSUE #362: Setup Danger to check code style before merging PR
We can setup [Danger](https://danger.systems/) to let us check some warnings before merging a PR.

### PR DESCRIPTION
**Pull request by tbaranes**
That aim to close #362 
In order to that, I had to create a github bot, and a gmail account. I will slack the credentials directly.

The Dangerfile is a first version, I think we should improve it following our future needs, but it's a good start.

Now, wait & see if everything is working 😬

### CODE REVIEW

**Comment by tbaranes** [comment]
> Danger does not have write access to the PR to set a PR status.

Still have to find what's happening here 🤔

**Comment by tbaranes** [comment]
I ended updating `travis.yml` too which seems to be working, but somehow, I can't get `Danger` write the status:

> Danger does not have write access to the PR to set a PR status.

Anyone has already experienced that or worked with github tokens?

**Comment by tbaranes** [comment]
All good but...

> Danger does not have write access to the PR to set a PR status.


Anyone has experienced with Danger or github tokens?

**Comment by mmadjer** [comment]
Not sure if this is related but you saw this issue?
https://github.com/danger/danger/issues/117

**Comment by tbaranes** [comment]
Yeah, I find that one when I looked into Danger issues, but didn't find any solution in it.
I'm waiting for travis to see if my last test did change something or not, otherwise I will probably answer in that thread or open a new issue to get help.

**Comment by JakeLin** [comment]
I am new to Danger. I have fired a ticket to Travis CI via support@travis-ci.com , will keep you guys posted once I got back anything.

**Comment by JakeLin** [comment]
Travis has fixed the build issue. It was an issue of their OS X infrastructure.

>Hey Jake,
>
>Thanks for reaching out and I'm sorry for this issue.
>
>Unfortunately, we are currently still working on fixing an incident with our OS X infrastructure:
>
>https://www.traviscistatus.com/incidents/nq0sf0srvx8s
>
>This is most probably the reason why your build is currently delayed. Sorry for the inconvenience.
>
>We are constantly giving status updates on the page linked above so I would suggest keeping an eye on it to see where we stand.
>
>Thank you for your understanding.
>
>Sincerely,
>
>-- Dominic.
>

@tbaranes can we merge this PR now? Or we still need to fix ?
>Danger does not have write access to the PR to set a PR status.

**Comment by tbaranes** [comment]
Danger is still not working, not sure due to the write access, not sure what we should do to fix it.

**Comment by JakeLin** [comment]
@tbaranes I am new  to Danger. They said it should be fixed in https://github.com/danger/danger/pull/380, but I don't know why our one can't pass?

**Comment by tbaranes** [comment]
We should open an issue there to ask more information about this. First time I setup a danger too (I just follow their steps). I will do it once I have more time to take care of this!

**Comment by JakeLin** [comment]
Thanks @tbaranes I need more time to learn how Danger works.

**Comment by tbaranes** [comment]
Issue opened there: https://github.com/danger/danger/issues/675

**Comment by tbaranes** [comment]
After some discutions with Danger Team and github support, it seems to be working! I'm merging this now, but it's possible the global system (to give write access to the bot) may change again later.

Also, it's now time to play around with the Dangerfile 🎉

**Comment by JakeLin** [comment]
Wa, thanks for following this up @tbaranes, big step 🎉🎉🎉 Danger team is very helpful too.

**Pull request merged**
