### PR TITLE
Release 5.2.0

### PR DESCRIPTION
**Pull request by JakeLin**
To support Xcode 10 and Swift 4.2, we are going to release 5.2.0 🎉 no breaking changes for Swift 4.1 and Xcode 9 😁

### CODE REVIEW

**Review by phimage — COMMENTED** [review]
👍

**Review by SD10 — APPROVED** [review]
Everything here and from #576 looks good to me 👍

**Review by tbaranes — APPROVED** [review]
Awesome!

**Comment by phimage** [comment]
- [x] Merged
- [x] tag added
- [x] cocoapod
- [x] branch deletion
- [x] release description https://github.com/IBAnimatable/IBAnimatable/releases

**Pull request merged**
