### PR TITLE
[F] NatGeo animation setted wrong center of UIView frame

### PR DESCRIPTION
**Pull request by edon2005**

### CODE REVIEW

**Review by JakeLin — CHANGES_REQUESTED** [review]
Thanks for fixing it. Can you please add an item to CHANGELOG.md? You can refer to https://github.com/IBAnimatable/IBAnimatable/blob/master/CHANGELOG.md#bugfixes thanks

**Comment by edon2005** [comment]
Yes, sure...

**Comment by edon2005** [comment]
@JakeLin Please check.

**Review by tbaranes — APPROVED** [review]

**Review by JakeLin — APPROVED** [review]
thanks again 👍

**Pull request merged**
