### PR TITLE
Xcode 8.0 beta 3

### PR DESCRIPTION
**Pull request by alexchan1680**
Hi JakeLin,  I am using IBAnimatable in my several projects and I am also using it in my project using swift3.
I have done some working on swift3 branch of your repository and it works for Xcode 8.0 beta 3 now. 
What do you think about this 😃 

Thank you.

### CODE REVIEW

**Comment by JakeLin** [comment]
Thanks @alexiosdev 👍

**Comment by JakeLin** [comment]
@alexiosdev Are you interested in helping us out with some features for swift 3? Please have a look at https://github.com/JakeLin/IBAnimatable/issues/221

**Comment by alexchan1680** [comment]
Hi, @JakeLin , Thank you for your invitation.
Unfortunately, I am heavily pressed with projects and I will surely take a look about it when I have time to do it.
Thank you again!

**Comment by JakeLin** [comment]
@alexiosdev Thanks, no worries. Please let me know if you are interested in some features and have some free time.

**Pull request merged**
