### PR TITLE
Updating 4.0.0 changelog

### PR DESCRIPTION
**Pull request by tbaranes**
- Updating the 4.0.0 releases notes (adding animations changes, missing credits, missing PRs references)

### CODE REVIEW

**Review by JakeLin — APPROVED** [review]
👍

**Review by JakeLin — APPROVED** [review]
👍 thanks for cleaning it up.

**Comment by JakeLin** [comment]
We may need to update the release note as well.

**Comment by tbaranes** [comment]
The update is from the release note, should be ok :)

**Comment by JakeLin** [comment]
@tbaranes cool, thanks.

**Pull request merged**
