### PR TITLE
Add more values for `PresentationModalSize`

### PR DESCRIPTION
**Pull request by phimage**
some proportional sizes added to enum

PS: I can wait swift 4 branch merging 

TODO
- [x] CHANGELOG

### CODE REVIEW

**Comment by phimage** [comment]
alternative implementation
Have one enum with name XXX (maybe ratio)
For size, return screen size divided by the ratio
But keep in `init` with `String`, keep all `String` cases and create the new enum for each

**Review by JakeLin — APPROVED** [review]
I like those enums. It should cover most of the cases. Especially comes with `GoldenRatio` 😉. Shall we merge it after we bring `swift4` branch in?

**Comment by phimage** [comment]
You can merge when you want. I can make a new PR if too much conflict.

**Review by SD10 — APPROVED** [review]
Great work @phimage 💯 Travis finally completed 😅

**Comment by JakeLin** [comment]
thanks @phimage we are ready for version 5

**Pull request merged**
