### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by raven**

### CODE REVIEW

**Comment by JakeLin** [comment]
Thanks Pete. I am going to document this project to describe how to prototype in Interface Builder and Swift Playground.

**Comment by JakeLin** [comment]
Great to have the first PR merged before Christmas.🎊

**Comment by raven** [comment]
Nice dude. Amazing to see how much interaction and animation can be made without custom code 👍

**Comment by mcilvena** [comment]
LGTM

**Comment by prasannag** [comment]
Jake, I thought that needed a IBAnimatable-evolution doc

**Pull request merged**
