### PR TITLE
codebeat badge

### PR DESCRIPTION
**Pull request by korzonek**
Is it fine to add codebeat badge to README? 

codebeat is automated code review tool for Swift,Ruby,Go & Python that helps get instant feedback on code quality. 

"Quick wins" suggested by codebeat could be a nice candidate for a pull request and help other developers become contributors.

FYI. To be fully open and honest. I'm co-founder of codebeat.

### CODE REVIEW

**Comment by JakeLin** [comment]
@korzonek Thanks for your PR, it is a very good service, we need to look at it to see how can we improve the current code quality. Especially the Animatable.swift file https://codebeat.co/projects/github-com-jakelin-ibanimatable/report_classes/swift-Animatable . I will consider to merge it later.

**Comment by korzonek** [comment]
@JakeLin thank you! We put a lot of love, passion and code into codebeat :) We launched at the beginning of this year so if you have any ideas or things you would like to see in codebeat please share it with us. It will help us prioritise our backlog :)

**Comment by JakeLin** [comment]
@korzonek I close this PR now and revisit it later. Thanks for your PR and the service.

**Comment by korzonek** [comment]
@JakeLin thank you! IBAnimatable is cool! Keep on doing a great job. 

BTW... please check us in 2-3 weeks. We will release excellent support for pull requests and enhanced version of Slack notification. Please don't treat is as shameless promotion I just feel very proud :)

**Pull request closed without merging**
