### PR TITLE
Add icon

### PR DESCRIPTION
**Pull request by lexrus**
According to #98 .
I've moved it to the first page.

Please review the [README.md](https://github.com/JakeLin/IBAnimatable/tree/feature/add_icon) as well.

img_0606

### CODE REVIEW

**Comment by tbaranes** [comment]
:tada: :birthday: :balloon:

**Comment by JakeLin** [comment]
Great, I like it very much. Can you please push the Sketch file to https://github.com/JakeLin/IBAnimatable-Misc project, do you thinkg using a separate project to save the assets/design files is a good idea?

**Comment by JakeLin** [comment]
@lexrus just curious, did you make the dot of "i" bigger in "IBAnimatable"? I can see you are using "SF UI Display" with Ultralight.

**Comment by lexrus** [comment]
For the Sketch files, that's nice to have a separated repo.
But the assets are reproducible with Sketch. It's not an elegant solution indeed.
Another maintainable solution is to create a branch called assets. Put all assets in it. Like what most popular libs did:
https://github.com/Alamofire/Alamofire/tree/assets

**Comment by lexrus** [comment]
No, it's PingFang SC, a new font Apple made for Yosemite.

**Comment by lexrus** [comment]
Never mind what I said. I guess it's okay to have the generated assets in Misc repo because we may have a lot of assets in the near feature. Switching branch is a little complicated in this case.
I'm working on a public machine. I'll do that tonight.

**Comment by JakeLin** [comment]
Thanks @lexrus Great work, I check out PingFang SC, for English characters, it is very close to SF Display UI. PingFang SC is fatter.
group

**Pull request merged**
