### PR TITLE
Fix the bug for using shadow for masked view 

### LINKED ISSUE #267: Shadows not working with Mask type.
I am trying to apply shadow on Mask type Circle seems like it's not working. Removing mask working properly.

### PR DESCRIPTION
**Pull request by JakeLin**
Fix #267 

Great thanks to @Abdul-Moiz for reporting and fixing this issue. I like the solution by using `shadowLayer.name = "shadowLayer-\(unsafeAddressOf(self))"`

Have updated the demo app to test them "User Interface" -> "Mask"

simulator screen shot sep 1 2016 9 45 20 pm

### CODE REVIEW

**Comment by tbaranes** [comment]
cool 👍

**Comment by JakeLin** [comment]
thanks @tbaranes

**Comment by tbaranes** [comment]
Just though, CHANGELOG missing!

**Comment by JakeLin** [comment]
@tbaranes I just changed it, it is in `feature/get-2-7-ready` branch.

**Pull request merged**
