### PR TITLE
Fixed right image in SideImageDesignable

### LINKED ISSUE #176: UITextField Right Image option is not showing Image ...!!
Hello sir,
UITextField left image is working properly but the right side image is not, i have attached the image file kindly have a review and lastly i would like to say it's a really great library to design...Great work 

Any Suggestion/help would be helpful .<br>
group

### PR DESCRIPTION
**Pull request by tbaranes**
Fixed #176

### CODE REVIEW

**Comment by tbaranes** [comment]
BuddyBuild is still failing 😢

**Comment by JakeLin** [comment]
@tbaranes thanks for you great quick fix. I will fix buddybuild again since it failed the signing again. 

@abdulKarim002 if you use CocoaPods, please point to the git repo now until we release 2.3. Here is an example, https://guides.cocoapods.org/using/the-podfile.html#from-a-podspec-in-the-root-of-a-library-repo thanks for reporting this issue.

**Comment by kodekarim** [comment]
hello @JakeLin Sir & @tbaranes thank you for your quick response and bug fix but sir i am using Carthage so how i can fix that issue using Carthage ? Any help !! Or it will be great sir if you release the 2.3 version shortly.

Thank you.

**Comment by JakeLin** [comment]
@abdulKarim002 you can use `github "JakeLin/IBAnimatable" "master"` to point to last commit on master branch.

Refer to http://stackoverflow.com/questions/31459847/carthage-how-to-get-the-very-latest-version-of-a-given-repository/31460014#31460014

**Comment by kodekarim** [comment]
Thank you sir.

**Pull request merged**
