### PR TITLE
Upgrade to support Swift 4.1 #no-public-changes 

### PR DESCRIPTION
**Pull request by JakeLin**
Upgrade to support Swift 4.1 and Xcode 9.3 (9E145). Related to #555

### CODE REVIEW

**Review by phimage — APPROVED** [review]
No more warning 👍

**Review by tbaranes — APPROVED** [review]
Nice move 😀

**Comment by phimage** [comment]
CHANGELOG.md 👿

**Comment by SD10** [comment]
Yeah CHANGELOG entry wouldn’t hurt even if no public changes. I’ve had quite a bit of trouble with Swift 4.1 on other libraries

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Pull request merged**
