### PR TITLE
Remove `DesignableGradientView`

### PR DESCRIPTION
**Pull request by JakeLin**
To keep the API simpler, remove `DesignableGradientView`

First breaking change, 😁😁

Reviewer @tbaranes 
Refer to https://github.com/JakeLin/IBAnimatable/issues/86

### CODE REVIEW

**Comment by tbaranes** [comment]
:tada:

**Comment by JakeLin** [comment]
close #87

**Comment by tbaranes** [comment]
Is it really closing this issue? That make the API nicer but fix the layer issue: it doesn't rotate...

**Comment by JakeLin** [comment]
Sorry, you are right, reopen issue #86

**Pull request merged**
