### PR TITLE
Added Placeholder for textView

### PR DESCRIPTION
**Pull request by learnwithgabbar**
Added placeholder for uitextview

### CODE REVIEW

**Comment by JakeLin** [comment]
Thanks for you PR. Sorry, can you use 2 spaces as a tab like what the other file is? It's very hard for me to see the difference 😂, thanks.

**Comment by JakeLin** [comment]
And we already have this feature, We did it in a protocol extension. Could you please advise more details about this PR?

**Comment by learnwithgabbar** [comment]
I have added the placeholder functionality through Interface builder

**Comment by JakeLin** [comment]
@techmehra It is already in master, please get the latest version of IBAnimatable and try out the demo app. Tap on "Forgot password" -> "User Interface" -> "Placeholder". It also supports Interface Builder. You can find it in "UserInterface.storyboard". If that's same as your PR. Can you close the current PR? If you have done more than that, please let me know the enhancement, thanks.

**Comment by learnwithgabbar** [comment]
@JakeLin Thanks for the Update

**Pull request closed without merging**
