### PR TITLE
Update SwiftPM manifest file

### PR DESCRIPTION
**Pull request by Jeehut**
This adds support for SwiftPM manifest based dependency managers. Specifically this adds support for installing via [Accio](https://github.com/JamitLabs/Accio) but will probably also work with SwiftPM once it's integrated into Xcode.

### CODE REVIEW

**Review by tbaranes — APPROVED** [review]

**Comment by Jeehut** [comment]
@tbaranes Anything holding you off from merging this?

**Comment by tbaranes** [comment]
Waiting for @JakeLin approval 😬

**Comment by tbaranes** [comment]
If no answer in the day, let's merge it.

**Review by devdev12 — APPROVED** [review]
LGTM

**Review by JakeLin — COMMENTED** [review]
👍  thanks for doing that

**Comment by JakeLin** [comment]
@Dschee thanks, it's merged 🎉

**Pull request merged**
