### PR TITLE
WIP: corner radius shadow fix

### PR DESCRIPTION
**Pull request by mmadjer**
Fix corner side radius in conjunction with shadow mask.
See issue #375.

### CODE REVIEW

**Comment by JakeLin** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Consider adding supporting documentation to this change. Documentation can be found in the <code>docs</code> directory.</td>
    </tr>
  </tbody>
</table>

### SwiftLint found issues

#### Warnings

File | Line | Reason |
| --- | ----- | ----- |
PresentationAnimationType.swift | 61 | Lines should not have trailing whitespace. 
TransitionAnimationType.swift | 249 | Lines should not have trailing whitespace. 
TransitionPresenterManager.swift | 20 | Lines should not have trailing whitespace. 


<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">danger</a>
</p>

**Review by JakeLin — CHANGES_REQUESTED** [review]
Thanks for picking up this 👍, your changes can preview shadow in Interface Builder when we use `layer.mask` for corner radius. we also need to change `CornerDesignable` as well as below:

```
public func configureCornerRadius() {
    if !cornerRadius.isNaN && cornerRadius > 0 {
      // Use `layer.mask` instead of `layer.cornerRadius` to support shadow
      layer.cornerRadius = 0.0

      // if a layer mask is specified, remove it
      layer.mask?.removeFromSuperlayer()

      layer.mask = cornerSidesLayer()
    }
  }
```

and something similar in `configureCornerRadius` of `public extension CornerDesignable where Self: UICollectionViewCell`.

Then we use `layer.mask` instead of `layer.cornerRadius` to draw corner radius for all cases including 4 corners. Which can support `UIButton` with a background image with a shadow. In this case, `MaskDesignable` will draw another shadow `layer`, you can find it in `configureMaskShadow` of `MaskDesignable`. This change actually is very good, because it can improve the rendering performance without **Color blended layers**. Thanks for you original change for supporting difference corner of radius, which makes that improvement in place.


We may need to change `AnimatableTextView` and `AnimatableLabel` as well. Although I never apply `cornerRadius` to `AnimatableLabel` 😁

**Comment by JakeLin** [comment]
simulator screen shot dec 20 2016 9 16 22 am
Before changing this, there is **Color blended layers** when use corner radius, it is OK since it is from UIKit.

simulator screen shot dec 20 2016 9 17 24 am
After changing this, there is no more  **Color blended layers** which can improve the performance a lot 🎉 , Great PR 👏👏👏

**Comment by JakeLin** [comment]
@tbaranes Do you know why Danger was using my account? I am not a bot thought 😁

**Comment by tbaranes** [comment]
Haha. I asked myself the same question when I saw it yesterday! Since it's using the right account in the other PR, let's see if that happen again.

**Comment by JakeLin** [comment]
I tried to fix the issue when using the background image with `AnimatableButton`.

Before 2d7edee

screen shot 2016-12-28 at 9 27 56 am

After 2d7edee

screen shot 2016-12-28 at 9 57 02 am

I can see there are some issues with `border` now. It is very hard to make all corner radius, mask and border work well together.

Better to not merge this branch and I need more time to find a better solution.

**Comment by tbaranes** [comment]
Just take a look at this PR, what's the status here? What's missing? Is there some regressions?

**Comment by mmadjer** [comment]
Sorry guys, I was on holiday and did not find time since I'm back to have a look into that.
I can see that @JakeLin did something, not quite sure what the status is.

**Comment by JakeLin** [comment]
This issue only happens in some very rare case. When we use the `backgroundImage` property of the `AnimatableButton` and set the `cornerRaidus` and `shadow` at the same time. It won't happen if we don't use the `backgroundImage` property.

The problem is caused by UIKit's *Clip to Bounds *, when we set it to `true` or `false`, it can only support some feature like `cornerRaidus` or `shadow`. So I think that's the problem of UIKit. 

To fix it, I tried to use `mask` for `cornerRaidus` not `layer.cornerRaidus`. @mmadjer has used `mask` for setting some corner of the `cornerRaidus` #356. I tried to apply the same method to all corners. It should work because we have used the method for `MaskDesignable`. Before @Abdul-Moiz find a way to use a separate layer for supporting shadow #267.  But after the commit 2d7edee, it ended up some issue like the border is miss( you can see it above).

We are not only fixing this issue; we try to find a good solution to support corner radius, mask and border, shadow work well together. I haven't found any other Open Source libraries can do that. I believe we are the best to support them together but still have some rare case like this issue. I think we are toward the right direction. But I still need more time to investigate and try out the solution. I also need some other eyes to find out the current problem (missing border issue).

**Comment by JakeLin** [comment]
I close this now since it only happens in a rare case. I may have a look again when I have more time.

**Pull request closed without merging**
