### PR TITLE
fix AnimatableModalViewController._dismissalAnimationType

### PR DESCRIPTION
**Pull request by kazyk**
Fixed an issue of setting dismissal animation type from IB.

### CODE REVIEW

**Review by JakeLin — APPROVED** [review]
👍  thanks

**Comment by JakeLin** [comment]
@kazyk thanks for fixing that,  can you please add an item to [CHANGELOG.md](https://github.com/IBAnimatable/IBAnimatable/blob/master/CHANGELOG.md) as well?

**Review by tbaranes — APPROVED** [review]

**Comment by kazyk** [comment]
@JakeLin
done 👍

**Comment by JakeLin** [comment]
@kazyk thanks, it is merged. Thanks to @tbaranes too.

**Pull request merged**
