### PR TITLE
Fix warnings from Xcode 9.1  and last swiftlint version #no-public-changes

### PR DESCRIPTION
**Pull request by tbaranes**

### CODE REVIEW

**Review by JakeLin — APPROVED** [review]
👍 cool, I prefer `private`

**Comment by tbaranes** [comment]
Not sure why travis did fail 🤔

**Comment by phimage** [comment]
For travis I see issue in Interactions.Storyboard but do not find the error description yet

With Xcode I have some issue like that on storyboards
```
file:///My/Home/path/IBAnimatable/IBAnimatableApp/IBAnimatableApp/Playground/Interactions/Interactions.storyboard: error: IB Designables: Failed to render and update auto layout status for UITableViewController (dfA-Oz-Rzp): The bundle “$(PRODUCT_NAME)” couldn’t be loaded because its executable couldn’t be located.
```
dfA-Oz-Rzp is the initial view controller

**Comment by JakeLin** [comment]
@phimage do you think that's an issue of travis?

**Comment by tbaranes** [comment]
Travis is failing on Danger, but the build and tests are passing. I'm merging.

**Comment by JakeLin** [comment]
Thanks @tbaranes 👍

**Pull request merged**
