### PR TITLE
Update storyboard to Xcode 8.3 #trivial

### PR DESCRIPTION
**Pull request by phimage**
Storyboards updated using Xcode 8.3

The aim is to not commit all this changes when doing other modifications into storyboards

### CODE REVIEW

**Review by tbaranes — APPROVED** [review]

**Comment by tbaranes** [comment]
Travis fails because Danger reports that there's no CHANGELOG entry, in this case, since we don't want to add an entry, you can just add `#trivial` to your PR title in order to make Danger ignore that condition.

**Comment by phimage** [comment]
ok thanks for the advice

**Review by JakeLin — APPROVED** [review]
👍

**Comment by JakeLin** [comment]
@phimage Can you please merge it when you think it is ready?

**Pull request merged**
