### PR TITLE
Predefined gradients

### PR DESCRIPTION
**Pull request by tbaranes**
Here are the predefined gradients (#24).
It's working perfectly well in the current state, but some unanswered questions (improvements?) are still persisting:
- The script that generates the enum / switch is just printing out the swift code. It's easy to use: just copy / paste them at the right place. I prefer this way since it's usable and more secure (we choose what we do), but maybe it would be better that the script erase the override the last output (directly in the project)? 
- `DesignableGradientView`: I didn't get why that class wasn't implemented the `GradientDesignable` directly instead of rewriting the process. I saw that `GradientDesignable` wasn't implemented the `startPoint` properly (the property is not used). Is there any reasons for these implementations or is it a bug? Whatever is the reason, it will probably need another PR to take of this

I'm waiting your feedback in order to improve all that stuff :)

PS: For the color extension, I just pick a working code on the net. If you have any preference for the implementation, I'm open to any suggestions!

### CODE REVIEW

**Comment by JakeLin** [comment]
👍, please merge it if you feel ready.

I like the idea to generate the code and paste it to the file manually. 

`DesignableGradientView` originally is a temporary view to wrap a layer within it. Will fix it. Add an issue against that problem. https://github.com/JakeLin/IBAnimatable/issues/81

**Comment by JakeLin** [comment]
@tbaranes please have a look, I have made some small modifications to your PR.

**Comment by tbaranes** [comment]
Good idea to make `UITableViewCell` and `AnimatableView` conform `GradientDesignable` :+1:

**Comment by JakeLin** [comment]
Shall we have a release/tag for that? That is a very useful feature. I am going to demonstrate this feature in Melbourne Cocoaheads

**Comment by tbaranes** [comment]
Awesome! Yes, we can make a new release. A lot of new features has been added since the last one. Do you want to create a CHANGELOG or directly explain what did change directly in the release desc?

**Comment by JakeLin** [comment]
CHANGELOG should be better and easier to maintain the history.

**Pull request merged**
