### PR TITLE
Avoid duplicates vibrancy view

### PR DESCRIPTION
**Pull request by tbaranes**
Fix @lastMove comments in #255

### CODE REVIEW

**Comment by lastMove** [comment]
Seems that you forget to commit AnimatableVibrancyView.swift ?

**Comment by tbaranes** [comment]
It's a private class in `BlurDesignable`, I didn't want to make it usable outside since it's only to identify the vibrancy view

**Comment by lastMove** [comment]
Oh ok, didn't saw it !
Seems all good

**Comment by JakeLin** [comment]
👍 well done.

**Pull request merged**
