### PR TITLE
Mask triangle

### PR DESCRIPTION
**Pull request by tbaranes**
screen shot 2016-02-06 at 18 03 48

### CODE REVIEW

**Comment by JakeLin** [comment]
Well done @tbaranes 👍

**Comment by lexrus** [comment]
I think we need a direction/angle property for this triangle so that we can draw icons for folders tree.
screen shot 2016-02-08 at 10 59 29 am

**Comment by JakeLin** [comment]
@tbaranes @lexrus  can we use `rotate` property although it is not rendered in IB properly yet?

**Comment by tbaranes** [comment]
Yes, I was thinking about rotating it directly. We can make it easier to use and add some parameters, but once again, we should find a happy ending for #8 before.

**Pull request merged**
