### PR TITLE
Get converted CACurrentMediaTime from layer.

### PR DESCRIPTION
**Pull request by lukas2**
PR for https://github.com/IBAnimatable/IBAnimatable/issues/540

### CODE REVIEW

**Review by JakeLin — APPROVED** [review]
👍 thanks for fixing this issue.

**Review by tbaranes — APPROVED** [review]
All good! Can you just add an entry to the changelog?

**Comment by lukas2** [comment]
Thanks for approving and all your work on this lib! 🙇‍♂️

Updated changelog. Do I have to create a new PR or can you merge it as it is? It shows up here, so I think it should work. (Github newbie here.. heh)

**Comment by JakeLin** [comment]
@lukas2 thanks again for updating the CHANGELOG.md. It is merged now 🎉. Thanks to @tbaranes for reviewing it as well.

**Pull request merged**
