### PR TITLE
Animatable presentation controller

### PR DESCRIPTION
**Pull request by tbaranes**
Related to #198 
This PR won't be merged in master but in `feature/presenter` since it's not ready to be released. There's still mandatory features missing, and that first PR implementing mainly the basics. Once merged, it will be easier to move forward.

**New in this PR:**
- Introducing `PresentationDesignable` which handle all the designable part of the `presentedVC`. Currently supporting: `cornerRadius`, `backgroundColor`, `opacity`, `blur`, `shadow` and `dismissOnTap`. Useful to customise the `dimmingView` and `presentedView`
- Introducing `PresentationAnimatable` which inherits of `UIPresentationController` and will be in charge of managing the present / dismiss animations, dimming view... and all the setup around presentation
- Introducing `AnimatablePresentatedViewController`, as the others, it just the `Animatable` type to present a controller
- Example project updates in order to test this feature

**Current state:**
- You can present an `AnimatablePresentatedViewController` programatically or using segues
- Every variables are customisable programatically as well as using IB
- Support 6 present / dismiss transitions: `Cover(Left, Right, Top, Bottom)`, `CrossDissolve`, `Flip`, `Invert`
- The `presentViewController` will always be presented in fullscreen, no support for custom size / position (next step)

**Questions / though:**
- Why `TransitionAnimatable` is an `Animatable` instead of `Designable`?
- I'm not really satisfy with the naming. Since the transitions and presentation view controller are together, it's complicated to understand which is what (when respecting apple's naming). There still some improvements to do on this
- How filtering animations for transitions and for presentations? For example, `Fade(.In)` must be available for the both, but in the current master implementation, it will work only for transitions because a presentation doesn't always have a `fromView`. So, two solutions:
  - Fix all the animations to support transitions as well as presentation. [Implementation of this solution for Fade](https://github.com/JakeLin/IBAnimatable/pull/247/commits/604f87421fcb413edc6e18342bf76d00c1695b59)
  - Create a new enums dedicated for presentation (which means a lot of duplication if we want the same animations), but it will make the code cleaner and the feature easier to understand.

Anyway, that's a first version, and there still a lot of work to do on it. Any feedbacks welcome!
Once that PR merged, it will be really easier to work all together on this :)

### CODE REVIEW

**Comment by lastMove** [comment]
Very useful feature !
Concerning your interrogations, I think the best is to adapt all animations to support both transitions and  Presentations.
It will be simpler and more maintainable

**Comment by tbaranes** [comment]
> Concerning your interrogations, I think the best is to adapt all animations to support both transitions and Presentations.

That's what I though first, but I changed my mind about this. Sadly, most of the current animators won't be reusable for a presentation animation because they are based on the fact that we have a `fromVC` and a `toVC` which is not the case when presenting...

So, if we keep solution 1, it will be hard for the user to know which enum they can use or not following if they are using a custom transition or presentation.

**Comment by tbaranes** [comment]
In the last commit, I implemented the second option (duplicate and differentiate a transition and a presentation instead of abstract them). If you want to see the main files diff, you should compare the following ones:
- `PresentationPresenter` vs `TransitionPresenter`
- `PresentationPresenterManager`vs `TransitionPresenterManager`
- `PresentationAnimationType` `TransitionAnimationType`
- `AnimatedPresenting` `AnimatedTransitioning`
  Each versus are pretty similar, but has subtil difference. As said above, most of the animators `TransitionAnimationType` can't be reused as a `PresentationAnimationType`. Presentation animations are really simpler, and there's not a lot of animation possible. 

Whichever the solution we choose in the end, we will need a context: are we doing a transition or a presentation? We can't escape from that, some part of the interfaces are completely related.

**Comment by tbaranes** [comment]
Closing in favour of #248

**Pull request closed without merging**
