### PR TITLE
Add class only requirement to Designable protocols

### PR DESCRIPTION
**Pull request by SD10**
### Summary of Pull Requests:
Changes the `Designable` protocols to be `class` only protocols

How should we handle the CHANGELOG entry? 

Technically this is an API Breaking change if someone was using these protocols on a `struct` for some reason.

### CODE REVIEW

**Review by JakeLin — APPROVED** [review]
👍

**Comment by JakeLin** [comment]
I don't think we can use those protocol in `struct`, it may have some case like we have to use `var view = view`. But that's not a breaking change. It is an improvement, right? 😂

**Comment by SD10** [comment]
I meant if a user was using our library like this:
```struct MyCustomAnimatableView: FillDesignable {}```
The protocols are public so people can access them directly if they want.
Idk why someone would use a `struct` for a UI element... but it IS possible 😅

**Comment by JakeLin** [comment]
I don't think someone would do that. If you think adding a breaking change will be safer, please go ahead, but only affect someone using it in a non-common way.

**Comment by tbaranes** [comment]
What's the advantage to do this?
(I'd like to approve it but can't do it on the application 😢)

**Comment by SD10** [comment]
@tbaranes There's no real advantage but generally UI elements should be classes.
When I'm writing Unit Tests I'm treating the element I'm testing as the protocol type.

However, the compiler can't ensure that the element is a reference type.
Therefore, I need to create a local copy of the element inside the scope of the test to modify it.

The problem is the compiler then gives me the warning to change `var` to `let` since it knows
it's a reference type and it was never modified.

If I change it to `let` the code won't compile. It says "cannot modify a let constant".

So I'm left with either using `let` and the code won't compile. 
Or using `var` and the code being littered with yellow warnings.

If you take a look at some of the old Travis build logs you will see these warnings.

EDIT:

This is currently failing because it broke something in the Demo App. I'll update it soon.

**Comment by SD10** [comment]
@JakeLin this is ready to go if it's all good with you.

**Review by JakeLin — APPROVED** [review]
👍

**Comment by JakeLin** [comment]
@SD10 yes, merged.

**Pull request merged**
