### PR TITLE
Add @IBDesignable views to public headers

### PR DESCRIPTION
**Pull request by DanielAsher**
This simple fix allows Carthage users to have access to IBAnimatable `@IBInpectables` and live views. Please see #543 for more details.

### CODE REVIEW

**Review by tbaranes — APPROVED** [review]

**Comment by toshi0383** [comment]
You might want to use XcodeGen to generate xcodeproj so we don't forget exposing newly added files.
But it can be in different PR.👌

**Review by JakeLin — APPROVED** [review]
👍 thanks for your PR, can you add an item to the CHANGELOG.md as well. Will be great if we can update the README.md to say we can support Carthage properly now.

**Comment by phimage** [comment]
Interesting solution 👍

**Comment by JakeLin** [comment]
@DanielAsher since you are a core contributor, can you merge it when you feel ready?

**Comment by DanielAsher** [comment]
@JakeLin thanks for your stewardship through this simple, but fraught, process 🙌

**Comment by JakeLin** [comment]
@DanielAsher Thanks again, welcome onboard 🎉

**Pull request merged**
