### PR TITLE
Frame is converted to window coordinate space to fix miscalculations in computed values

### PR DESCRIPTION
**Pull request by redent**
Fix for #411

### CODE REVIEW

**Comment by JakeLin** [comment]
@redent thank you very much for reporting the issue and fixing it 👍. Could you please fix some small code style issues? And update the [CHANGLOG.md](https://github.com/IBAnimatable/IBAnimatable/blob/master/CHANGELOG.md#bugfixes) file here?

@tbaranes could you please review this PR?

**Review by tbaranes — APPROVED** [review]
Looks cool beside the code style warnings 👍 

We are using [SwiftLint](https://github.com/realm/SwiftLint) to prevent code style syntax error as reported by Danger. You can install it if you want to see the warnings directly in Xcode!

**Comment by tbaranes** [comment]
Not sure why travis failed to install Danger, but the failure is not related to the PR _directly_.

**Comment by tbaranes** [comment]
I'm merging this, I will update the CHANGELOG and fix SwiftLint warnings on master directly.
Thanks for your contribution @redent !

The travis failure is due to the missing changelog, nothing blocking to merge it.

**Comment by redent** [comment]
Thanks for the fast response. Glad I could help.

**Comment by JakeLin** [comment]
@tbaranes I found now we can push to other contribute's fork if they gave us permission like I did in #407 . Next time, we can try to push to the fork first and still see the diff in the PR. But we can push master as we are internal contributors 😉

**Comment by JakeLin** [comment]
@redent thanks for your PR 👍. 
@tbaranes  thanks for following it up 💪.

**Pull request merged**
